export interface Quote {
  symbol: string, // SBER,
  exchange: string, // MOEX,
  description: string, // Сбербанк России ПАО ао,
  prev_close_price: number, // 295,
  last_price: number, // 292.6,
  last_price_timestamp: number, // 1640770239,
  change: number, // -2.4,
  change_percent: number, // -0.81,
  high_price: number, // 295.3,
  low_price: number, // 292.34,
  accruedInt: number, // 0,
  accrued_interest: number, // 0,
  volume: number, // 14291950,
  open_interest: number, // null,
  ask: number, // 292.6,
  bid: number, // 292.5,
  ask_vol: number, // 90,
  bid_vol: number, //355,
  ob_ms_timestamp: number, // null,
  open_price: number, // 295.05,
  yield: number, // null,
  lotsize: number, // 10,
  lotvalue: number, // 2926,
  facevalue: number, // 3,
  type: string, // CS,
  total_bid_vol: number, // 243860,
  total_ask_vol: number, // 357187
}
