export enum ScalperOrderBookCommands {
  centerOrderBook = 'centerOrderbook',
  cancelLimitOrdersAll = 'cancelLimitOrdersAll',
  closePositionsByMarketAll = 'closePositionsByMarketAll',
  cancelLimitOrdersCurrent = 'cancelLimitOrdersCurrent',
  cancelStopOrdersCurrent = 'cancelStopOrdersCurrent',
  closePositionsByMarketCurrent = 'closePositionsByMarketCurrent',
  sellBestOrder = 'sellBestOrder',
  buyBestOrder = 'buyBestOrder',
  sellMarket = 'sellMarket',
  buyMarket = 'buyMarket',
  reversePositionsByMarketCurrent = 'reversePositionsByMarketCurrent',
  sellBestBid = 'sellBestBid',
  buyBestAsk = 'buyBestAsk',
  increaseScale = 'increaseScale',
  decreaseScale = 'decreaseScale',
}
